#!/bin/sh

FNAME=cr2res_manpages.tex

echo "\section{Recipe man-pages}\label{sec:manpages}" > $FNAME

cat <<EOT >> $FNAME

%% DO NOT EDIT THIS FILE, IT GETS MADE BY man2tex.sh

The following are auto-generated chapters that contain the manual-pages
of each recipe. These can be viewed at any time on the command-line
with
\begin{verbatim}
    esorex --man-page <recipe>
\end{verbatim}
where \texttt{<recipe>} stands for the recipe name.

In order to avoid duplication of information, this serves as reference for
for inputs, outputs and parameters of each recipe.
Explanations and context for algorithms and non-obvious parameters are provided
in the appropriate chapters.

EOT

esorex --recipes | grep cr2re | cut -b3-23 | sort -u | while read rec; do
    resc=$(echo $rec | sed s/_/\\\\_/g)
    printf "\subsection{${resc}}\n" >> $FNAME
    printf "\small\n" >> $FNAME
    printf "%sbegin{verbatim}\n" "\\" >> $FNAME
    esorex --man-page $rec | tail -n+4 | head -n-31  >> $FNAME
    printf "%send{verbatim}\n" "\\" >> $FNAME
    printf "%snormalsize\n" "\\" >> $FNAME

done